version: 2.1

orbs:
  architect: giantswarm/architect@4.31.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: aws-rolling-node-operator
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          context: "architect"
          name: push-aws-rolling-node-operator-to-quay
          image: "quay.io/giantswarm/aws-rolling-node-operator"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-aws-rolling-node-operator-to-docker
          image: "docker.io/giantswarm/aws-rolling-node-operator"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-docker:
          context: "architect"
          name: push-aws-rolling-node-operator-to-aliyun
          image: "giantswarm-registry.cn-shanghai.cr.aliyuncs.com/giantswarm/aws-rolling-node-operator"
          username_envar: "ALIYUN_USERNAME"
          password_envar: "ALIYUN_PASSWORD"
          requires:
            - go-build
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-aws-rolling-node-operator-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "aws-rolling-node-operator"
          requires:
            - push-aws-rolling-node-operator-to-quay
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "aws-rolling-node-operator"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-aws-rolling-node-operator-to-quay
            - push-aws-rolling-node-operator-to-docker
            - push-aws-rolling-node-operator-to-aliyun
            - push-aws-rolling-node-operator-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

