aws:
  accessKeyID: accesskey
  secretAccessKey: secretkey
  region: region

installation:
  name: name

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
image:
  name: "giantswarm/aws-rolling-node-operator"
  tag: "[[ .Version ]]"
registry:
  domain: docker.io

pod:
  user:
    id: 1000
  group:
    id: 1000

resources:
  limits:
    cpu: 250m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 250Mi


# Add seccomp to pod security context
podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  seccompProfile:
    type: RuntimeDefault

serviceMonitor:
  enabled: true
  # -- (duration) Prometheus scrape interval.
  interval: "60s"
  # -- (duration) Prometheus scrape timeout.
  scrapeTimeout: "45s"
